---

- name: install postgis extension
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
  - postgresql-9.3-postgis-2.1
